name: apollo
description: App for API and backend management.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  swipe_cards: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  splashscreen:
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  firebase_database: ^6.1.2
  fluttertoast:


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/alt__main.png"

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/logo/
   - assets/images/

  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-VariableFont_wght.ttf
    - family: Mate
      fonts:
        - asset: assets/fonts/Mate-Regular.ttf
    - family: Serif
      fonts:
        - asset: assets/fonts/SourceSerifPro-ExtraLight.ttf
 
